pool:
  vmImage: 'ubuntu-16.04'

strategy:
  matrix:
    9.2_3.6:
      containerImage: pymor/dealii_py3.6:93e0f6225eeaae049ca3b392f77cd8d4150ee590
    9.2_3.7:
      containerImage: pymor/dealii_py3.7:93e0f6225eeaae049ca3b392f77cd8d4150ee590
    9.2_3.8:
      containerImage: pymor/dealii_py3.8:93e0f6225eeaae049ca3b392f77cd8d4150ee590

container: $[ variables['containerImage'] ]

steps:
- script: ./.ci/travis.script.bash
