pool:
  vmImage: 'ubuntu-20.04'

strategy:
  matrix:
    9.3_3.7:
      containerImage: pymor/dealii_py3.7:7192db98b77083ef124fc0b90c4a607a258b232d
    9.3_3.8:
      containerImage: pymor/dealii_py3.8:7192db98b77083ef124fc0b90c4a607a258b232d
    9.3_3.9:
      containerImage: pymor/dealii_py3.9:7192db98b77083ef124fc0b90c4a607a258b232d

container: $[ variables['containerImage'] ]

steps:
- script: ./.ci/travis.script.bash
