---
name: Tests
on:
  # run tests on pull requests for main and release branches
  # and (after a merge) on the target branch
  push:
    branches:
      - main
      - create-pull-request/patch*
  pull_request:
  merge_group:
    types:
      - checks_requested
jobs:
  bugout:
    name: Cancel superseded jobs
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          all_but_latest: true
          # also works on 'pull_request' targets
          ignore_sha: true
          access_token: ${{ github.token }}
  runtests:
    name: Run tests
    runs-on: ubuntu-22.04
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4
      - name: install deal.II
        run: |
          sudo apt update
          sudo apt install libdeal.ii-dev
      - name: install uv
        uses: astral-sh/setup-uv@v5
      - name: build
        run: uv build
      - name: pytest
        run: uv run --extra=test pytest
